"""init schema

Revision ID: 0f4c1b60c958
Revises: 
Create Date: 2026-05-17 01:29:52.376208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4c1b60c958'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('indicator', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'indicator', 'year')
    )
    op.create_index(op.f('ix_health_metrics_country_code'), 'health_metrics', ['country_code'], unique=False)
    op.create_index(op.f('ix_health_metrics_id'), 'health_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_health_metrics_indicator'), 'health_metrics', ['indicator'], unique=False)
    op.create_index(op.f('ix_health_metrics_year'), 'health_metrics', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_metrics_year'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_indicator'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_id'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_country_code'), table_name='health_metrics')
    op.drop_table('health_metrics')
    # ### end Alembic commands ###
